### ISSUE TITLE
How safe is it ?

### ISSUE THREAD

**Issue by michalskuza** [lukasz-szewc/simple-encryption-tool#1]

**Comment by lukasz-szewc** [comment]
At this point of time security is compromised, because Cipher constructor use default value of both: salt and initial vector. These values are hard coded. It has advantage : it works

**Comment by michalskuza** [comment]
Any ideas how to solve it ?

**Comment by lukasz-szewc** [comment]
Yes - generate salt every single time and persist it.

**Comment by michalskuza** [comment]
This article is resourceful and might be useful

http://ithare.com/password-hashing-why-and-how/

**Comment by michalskuza** [comment]
how's progress ?

**Comment by lukasz-szewc** [comment]
Not planning to change anything in foreseeable future. Feel free to fork.
